# Generated by Django 5.1.15 on 2026-04-03 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Our Twitter Guy'", max_length=255)),
                ('agent_type', models.CharField(help_text="Blueprint type — determines the agent's behavior", max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions layered on top of the blueprint prompts')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-agent config (browser cookies, API keys, etc.)')),
                ('auto_exec_hourly', models.BooleanField(default=False, help_text='Whether this agent auto-executes hourly tasks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.department')),
                ('superior', models.ForeignKey(blank=True, help_text='Superior agent that can delegate tasks to this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='agents.agent')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='awaiting_approval', max_length=20)),
                ('auto_execute', models.BooleanField(default=False)),
                ('exec_summary', models.TextField(blank=True, help_text='Short description of what to do')),
                ('step_plan', models.TextField(blank=True, help_text='Detailed step-by-step plan')),
                ('report', models.TextField(blank=True, help_text='What was actually done')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.agent')),
                ('created_by_agent', models.ForeignKey(blank=True, help_text='Set when a superior agent delegates this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_tasks', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
