# Generated by Django 5.1.15 on 2026-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0003_projectconfig_project_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['department', '-is_leader', 'name']},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='superior',
        ),
        migrations.AddField(
            model_name='agent',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Leader agent for the department. Creates and delegates tasks to workforce agents.'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_leader', True)), fields=('department',), name='unique_leader_per_department'),
        ),
    ]
