# Generated by Django 5.1.15 on 2026-04-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_remove_agent_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='internal_state',
            field=models.JSONField(blank=True, default=dict, help_text='Agent-managed state (last_tweet_at, emails_sent_today, etc.). Read/written by blueprints.'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='proposed_exec_at',
            field=models.DateTimeField(blank=True, help_text='Agent-proposed optimal execution time', null=True),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed execution time (set on approval)', null=True),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, help_text='Set when the department leader delegates this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_tasks', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('planned', 'Planned'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='awaiting_approval', max_length=20),
        ),
    ]
