# Generated by Django 5.1.15 on 2026-04-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_internal_state_agenttask_proposed_exec_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='auto_exec_hourly',
        ),
        migrations.AddField(
            model_name='agent',
            name='auto_actions',
            field=models.JSONField(blank=True, default=dict, help_text='Maps command names to auto-execute booleans, e.g. {"engage-tweets": true, "post-content": false}. Defaults all false.'),
        ),
    ]
