# Generated by Django 5.1.15 on 2026-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_auto_exec_hourly_agent_auto_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='token_usage',
            field=models.JSONField(blank=True, help_text='Token usage from Claude API: {model, input_tokens, output_tokens, cost_estimate}', null=True),
        ),
    ]
