# Generated by Django 5.1.15 on 2026-04-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text="This task can't run until the blocker completes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='agents.agenttask'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='command_name',
            field=models.CharField(blank=True, help_text="Command on the agent's blueprint this task executes. Used for auto_actions lookup.", max_length=100),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('awaiting_dependencies', 'Awaiting Dependencies'), ('planned', 'Planned'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='awaiting_approval', max_length=30),
        ),
    ]
