# Generated by Django 5.1.15 on 2026-04-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_agenttask_blocked_by_agenttask_command_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["-created_at"], name="task_created_desc"),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["status", "-created_at"], name="task_status_created"),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["agent", "-created_at"], name="task_agent_created"),
        ),
    ]
