# Generated by Django 5.1.15 on 2026-04-04 20:18
# Originally added briefing FK to AgentTask, but the Briefing model was later
# removed.  Migration 0011 removes this field.  Replaced with a no-op so the
# migration graph stays intact without a dangling reference to projects.briefing.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_add_task_indexes"),
    ]

    operations = []
