# Generated by Django 5.1.15 on 2026-04-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_add_task_indexes"),
        ("projects", "0012_add_briefings"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="briefing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.briefing",
            ),
        ),
    ]
