# Generated by Django 5.1.15 on 2026-04-04 22:34

from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    Agent = apps.get_model("agents", "Agent")
    Agent.objects.filter(is_active=True).update(status="active")
    Agent.objects.filter(is_active=False).update(status="inactive")


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_add_briefings"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[
                    ("provisioning", "Provisioning"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("failed", "Failed"),
                ],
                default="provisioning",
                help_text="Agent lifecycle status",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_is_active_to_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="agent",
            name="is_active",
        ),
    ]
