# Generated by Django 5.1.15 on 2026-04-04 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_agent_status_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agenttask",
            name="task_created_desc",
        ),
        migrations.RemoveIndex(
            model_name="agenttask",
            name="task_status_created",
        ),
        migrations.RemoveIndex(
            model_name="agenttask",
            name="task_agent_created",
        ),
        # briefing field removal is a no-op — field was never added (0009 was
        # replaced with a no-op after the Briefing model was removed).
    ]
