# Generated by Django 5.1.15 on 2026-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_remove_agenttask_task_created_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="auto_approve_all",
            field=models.BooleanField(
                default=False, help_text="When true, all tasks for this agent skip approval and execute immediately."
            ),
        ),
    ]
