# Generated by Django 5.1.15 on 2026-04-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0012_auto_approve_all"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="auto_approve_all",
            new_name="auto_approve",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="auto_actions",
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="command_name",
            field=models.CharField(
                blank=True, help_text="Command on the agent's blueprint this task executes.", max_length=100
            ),
        ),
    ]
