# Generated by Django 5.1.15 on 2026-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0013_remove_auto_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="review_score",
            field=models.FloatField(blank=True, help_text="Review score 0.0-10.0 from structured verdict", null=True),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="review_verdict",
            field=models.CharField(
                blank=True, help_text="Structured verdict from reviewer: APPROVED or CHANGES_REQUESTED", max_length=20
            ),
        ),
    ]
