# Generated by Django 5.1.15 on 2026-04-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0014_add_review_verdict_fields"),
        ("projects", "0017_sprint_source_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.sprint",
            ),
        ),
    ]
