# Generated by Django 5.1.15 on 2026-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0015_agenttask_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="outreach",
            field=models.BooleanField(
                default=False, help_text="Whether this agent handles outreach delivery (email, LinkedIn, etc.)"
            ),
        ),
    ]
