# Generated by Django 5.1.15 on 2026-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0019_remove_auto_approve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttask",
            name="command_name",
            field=models.CharField(
                help_text="Command on the agent's blueprint this task executes. Required.", max_length=100
            ),
        ),
    ]
