# Generated by Django 5.1.15 on 2026-04-10 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0020_command_name_required"),
        ("projects", "0023_output_unique_by_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClonedAgent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "clone_index",
                    models.IntegerField(help_text="0-based index for identification within a fan-out batch"),
                ),
                (
                    "internal_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Clone-specific working state (target_count, cumulative profiles, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="The agent this clone inherits blueprint/instructions/config from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clones",
                        to="agents.agent",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        help_text="Sprint this clone is scoped to — destroyed when sprint completes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloned_agents",
                        to="projects.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["sprint", "parent", "clone_index"],
            },
        ),
        migrations.AddField(
            model_name="agenttask",
            name="cloned_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this task runs on behalf of a cloned agent instance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="agents.clonedagent",
            ),
        ),
    ]
