# Generated by Django 5.1.15 on 2026-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0021_cloned_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="retry_count",
            field=models.PositiveSmallIntegerField(default=0, help_text="Number of retries attempted"),
        ),
    ]
