# Generated by Django 5.1.15 on 2026-04-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0022_add_retry_count_to_agenttask"),
        ("projects", "0026_cascade_sprint_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttask",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.sprint",
            ),
        ),
    ]
