# Generated by Django 5.1.15 on 2026-04-03 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('proposal', models.JSONField(blank=True, help_text='The proposed departments, agents, and documents.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('token_usage', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_proposals', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('text', 'Text')], default='file', max_length=10)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('file_key', models.CharField(blank=True, help_text='Storage path — private, never expose directly.', max_length=512)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hex digest of file content.', max_length=64)),
                ('raw_content', models.TextField(blank=True, help_text='For text sources: the raw text. For files: unprocessed extracted text.')),
                ('extracted_text', models.TextField(blank=True, help_text='Cleaned text ready for Claude analysis.')),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_hash__gt', '')), fields=('user', 'content_hash'), name='unique_content_per_user')],
            },
        ),
    ]
