# Generated by Django 5.1.15 on 2026-04-03 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_bootstrapproposal_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Hotel Berlin Google Account'", max_length=255)),
                ('google_email', models.EmailField(blank=True, help_text='Gmail address agents act on behalf of', max_length=254)),
                ('google_credentials', models.JSONField(blank=True, default=dict, help_text='OAuth tokens, refresh token, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.ForeignKey(blank=True, help_text='Shared config (Google credentials, etc.). One config can serve multiple projects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectconfig'),
        ),
    ]
