# Generated by Django 5.1.15 on 2026-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_social_media_to_marketing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectconfig',
            options={'verbose_name': 'project config', 'verbose_name_plural': 'project configs'},
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='google_credentials',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='google_email',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Project-wide config — validated against PROJECT_CONFIG_SCHEMA'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(default='marketing', help_text='Department type — must match a blueprint folder (e.g. social_media, engineering)', max_length=50),
        ),
    ]
