# Generated by Django 5.1.15 on 2026-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_members_alter_bootstrapproposal_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('active', 'Active')], db_index=True, default='setup', max_length=10),
        ),
    ]
