# Generated by Django 5.1.15 on 2026-04-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('general', 'General'), ('research', 'Research'), ('branding', 'Branding'), ('strategy', 'Strategy'), ('campaign', 'Campaign')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
