# Generated by Django 5.1.15 on 2026-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_document_doc_type_document_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
