# Generated by Django 5.1.15 on 2026-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Department-level config — cascades to agents'),
        ),
    ]
