# Generated by Django 5.1.15 on 2026-04-04 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_add_briefings"),
        ("projects", "0012_add_briefings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("research", "Research"),
                    ("branding", "Branding"),
                    ("strategy", "Strategy"),
                    ("campaign", "Campaign"),
                    ("voice_profile", "Voice Profile"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text='e.g. "logline", "treatment", "contract_draft", "v2"', max_length=50
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("fountain", "Fountain"),
                            ("plaintext", "Plain Text"),
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("other", "Other"),
                        ],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file_key",
                    models.CharField(
                        blank=True, help_text="Storage path -- private, never expose directly.", max_length=500
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outputs",
                        to="agents.agenttask",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="projects.department",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="projects.output",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outputs", to="projects.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
