# Generated by Django 5.1.15 on 2026-04-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_add_output_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="briefing",
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("research", "Research"),
                    ("branding", "Branding"),
                    ("strategy", "Strategy"),
                    ("campaign", "Campaign"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Output",
        ),
    ]
