# Generated by Django 5.1.15 on 2026-04-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_remove_source_briefing_alter_document_doc_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("research", "Research"),
                    ("branding", "Branding"),
                    ("strategy", "Strategy"),
                    ("campaign", "Campaign"),
                    ("voice_profile", "Voice Profile"),
                    ("concept", "Concept"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
    ]
