# Generated by Django 5.1.15 on 2026-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_add_concept_voice_profile_doc_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Claude-generated summary of the full source content. Used in prompts instead of truncated text.",
            ),
        ),
    ]
