# Generated by Django 5.1.15 on 2026-04-05 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_source_summary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Briefing",
        ),
    ]
