# Generated by Django 5.1.15 on 2026-04-05 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_source_summary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField(help_text="The work instruction from the user")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("paused", "Paused"), ("done", "Done")],
                        db_index=True,
                        default="running",
                        max_length=10,
                    ),
                ),
                (
                    "completion_summary",
                    models.TextField(blank=True, help_text="Leader-provided summary when marking sprint done"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sprints", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("departments", models.ManyToManyField(related_name="sprints", to="projects.department")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sprints", to="projects.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="source",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="projects.sprint",
            ),
        ),
    ]
