# Generated by Django 5.1.15 on 2026-04-05 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_delete_briefing"),
        ("projects", "0017_sprint_source_sprint"),
    ]

    operations = []
