# Generated by Django 5.1.15 on 2026-04-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_merge_0017_delete_briefing_0017_sprint_source_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="consolidated_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consolidated_from",
                to="projects.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sprint_progress", "Sprint Progress"),
                    ("sprint_summary", "Sprint Summary"),
                    ("monthly_archive", "Monthly Archive"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="projects.sprint",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("research", "Research"),
                    ("branding", "Branding"),
                    ("strategy", "Strategy"),
                    ("campaign", "Campaign"),
                    ("voice_profile", "Voice Profile"),
                    ("concept", "Concept"),
                    ("sprint_progress", "Sprint Progress"),
                    ("sprint_summary", "Sprint Summary"),
                    ("monthly_archive", "Monthly Archive"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
    ]
