# Generated by Django 5.1.15 on 2026-04-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_document_consolidation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("research", "Research"),
                    ("branding", "Branding"),
                    ("strategy", "Strategy"),
                    ("campaign", "Campaign"),
                    ("voice_profile", "Voice Profile"),
                    ("concept", "Concept"),
                    ("sprint_progress", "Sprint Progress"),
                    ("sprint_summary", "Sprint Summary"),
                    ("monthly_archive", "Monthly Archive"),
                    ("stage_deliverable", "Stage Deliverable"),
                    ("stage_research", "Stage Research & Notes"),
                    ("stage_critique", "Stage Critique"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
    ]
