# Generated by Django 5.1.15 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_document_stage_doc_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Locked documents are protected from consolidation and archiving by automated processes.",
            ),
        ),
    ]
