# Generated by Django 5.1.15 on 2026-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_agenttask_sprint'),
        ('projects', '0022_output_model_rewrite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='output',
            name='one_output_per_department_per_sprint',
        ),
        migrations.AddConstraint(
            model_name='output',
            constraint=models.UniqueConstraint(fields=('sprint', 'department', 'label'), name='one_output_per_department_per_sprint_per_label'),
        ),
    ]
