# Generated by Django 5.1.15 on 2026-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_output_unique_by_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="department_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-department pipeline state keyed by department ID. Reset clears this.",
            ),
        ),
    ]
