# Generated by Django 5.1.15 on 2026-04-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0025_add_sprint_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.sprint",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="projects.sprint",
            ),
        ),
    ]
