# Generated by Django 5.1.15 on 2026-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0026_cascade_sprint_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="priority",
            field=models.CharField(
                choices=[
                    ("essential", "Essential"),
                    ("important", "Important"),
                    ("regular", "Regular"),
                    ("minor", "Minor"),
                ],
                db_index=True,
                default="regular",
                help_text="Controls which agents see this source and in what form.",
                max_length=10,
            ),
        ),
    ]
